baseURL = "https://missberg.github.io/eir-open/"
languageCode = "en-us"
title = "Eir Open"
theme = "github.com/thegeeklab/hugo-geekdoc"

[module]
  [[module.imports]]
    path = "github.com/thegeeklab/hugo-geekdoc"
    disable = false

[params]
  geekdocNav = true
  geekdocSearch = true
  geekdocAnchor = true
  geekdocRepo = "https://github.com/eir-space/eir-open"
  geekdocEditPath = "edit/main/hugo/content"
  geekdocBreadcrumb = true

  customCss = ["/css/custom.css"]
  customJs = []

  [params.geekdocOverrides]
    "style.color" = "#1e5f6d"

[outputs]
  home = ["HTML", "RSS"]
